FROM node:14-stretch-slim as build
ARG REACT_APP_WEB_API
ARG REACT_APP_GOOGLE_ID
ARG REACT_APP_FACEBOOK_ID
ENV REACT_APP_WEB_API=$REACT_APP_WEB_API
ENV REACT_APP_GOOGLE_ID=$REACT_APP_GOOGLE_ID
ENV REACT_APP_FACEBOOK_ID=$REACT_APP_FACEBOOK_ID
WORKDIR /app
COPY . /app
RUN npm install && npm run build

FROM nginx:latest
COPY --from=build /app/build /usr/share/nginx/html
