version: '3.8'

services:
  app:
    image: nakfl/online-caro-react:latest
    environment:
      REACT_APP_WEB_API: http://68.183.239.178:6969
      REACT_APP_GOOGLE_ID: 518404312823-ibh4ph48o4p3ad7b6f4jd4eoiv6m4o7l.apps.googleusercontent.com
      REACT_APP_FACEBOOK_ID: 703530593917463
      REACT_APP_JWT_SECRET: anhem1nha
    command: sh -c "npm start"
    ports:
      - 80:3000
