version: '3.8'

services:
  server:
    image: nakfl/back-end-live-tutor:latest
    depends_on:
      - database
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://postgres:password@database:5432/live-tutor
      DATABASE_DIALECT: postgres
      PORT: 6969
      JWT_SECRET: anhem1nha
      JWT_EXPIRATION_MINUTES: 30
      JWT_REFRESH_EXPIRATION_DAYS: 30
    command: sh -c "./wait-for-it.sh database:5432 && npm run migrate && npm run migrate:seed && npm start"
    ports:
      - 6969:6969

  database:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: live-tutor
